# Use postgres/example user/password credentials
version: "3.1"

services:
  # mysql-dev: 
  #   image: mysql
  #   restart: always
  #   ports: 
  #     - 3308:3308
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql:rw
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_DATABASE: webapp
    
  pgdb:
    image: postgres
    restart: always
    ports: 
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webapp

    volumes:
     - "./data:/var/lib/postgresql/data"
    
  adminer:
    image: adminer
    ports:
      - 8080:8080